### ISSUE TITLE
libvirt_pool fails on centos 6.5

### ISSUE THREAD

**Issue by Xylakant** [thias/puppet-libvirt#31]
Using the libvirt_pool type on centos 6.5 fails with 

````
Error: Could not autoload puppet/provider/exec/windows: can't convert Hash into Integer
Error: Could not autoload puppet/type/exec: Could not autoload puppet/provider/exec/windows: can't convert Hash into Integer
````
The problem is probably related to the outdated ruby 1.8.7 on CentOS 6.5. The issue gets triggered by the `include REXML` line in the provider class (https://github.com/thias/puppet-libvirt/blob/master/lib/puppet/provider/libvirt_pool/virsh.rb#L4). This line can be removed if in line [150](https://github.com/thias/puppet-libvirt/blob/master/lib/puppet/provider/libvirt_pool/virsh.rb#L150) the `Document.new` is replaced with `REXML::Document.new`. This fixes the issue.

Will try to provide a proper PR next week, just wanted to record this while it's fresh.

**Comment by thias** [comment]
Should be fixed. See #32.

**Comment by deepumalladi** [comment]
Hi I am facing same issue when i am running puppet agent -t --noop command.
my puppet version is 3.8.2 and i am using it on RHEL6U6( both master ans agent). Can some please explain in detail what exactly to be done? because i am not able to figure out virsh.rb file in eiher of mastger or agent. can you let me know the exact path?
